### ISSUE TITLE
fetch_data method returns no results

### ISSUE THREAD

**Issue by leeprevost** [crvaden/NOAA_API_v2#1]
I can't get the fetch_data method to return results even if I use the example listed in the readme.

weather_data = data.fetch_data(datasetid='GHCND', locationid='ZIP:28801', startdate='2010-05-01', enddate='2010-05-02', limit=1000)

when i run this with my own api_key, I get valid responses for other methods but nothing is returned for this call.  returns empty dataset.

**Comment by italian-buzz** [comment]
I have the same issue.  Seems like the requests program has problems with passing "locationid='ZIP:28801" as a parameter. Here's what I found:

  1.  If I use NOAA_AP_v2 and I remove the  "locationid='ZIP:28801',", I do get responses. 
  2.  If I use requests without passing params, I do get responses.
    url  = "http://www.ncdc.noaa.gov/cdo-web/api/v2/data?
    datasetid=GHCND&locationid=ZIP:28801&startdate=2010-05-01&enddate=2010-05-02&limit=1000"
    headers = {'token': 'MyToken'}
    response = requests.get(url, headers = headers)
   3.  If I use requests and pass the "locationid='ZIP:28801'," as a parameter, I do not get responses.
     base_url = 'http://www.ncdc.noaa.gov/cdo-web/api/v2/'
     request_type = 'data'
     url = base_url + request_type
     payload = {'datasetid': 'GHCND', 'locationid': 'ZIP:54403', 'startdate': '2010-05-01', 'enddate': '2010-05-01'}
     response = requests.get(url, headers = headers, params=payload)
     response = response.json()
  4.  If I use requests and leave out the locationid, I do get responses.

**Comment by crvaden** [comment]
I can take a look at it.

**Comment by crvaden** [comment]
It looks like the old http url is causing issues.  Updated the request url to the https endpoint and it appears to be resolving the issue.  Try pulling again and letting me know if this fixes your issue.

**Comment by italian-buzz** [comment]
Yes, that fixed it.  Thank you.
